#!/bin/sh
alias s='\/usr/bin/sudo '  # the backslash ignores aliases for /usr/bin/sudo (security)
#compdef s='sudo'
alias se='\/usr/bin/sudo -E '  # the space allows us to chain aliases
#compdef se='sudo'

# alias yu='yaourt'
# # compdef yu='pacman'
# alias yus='yaourt -Sy'
# alias yuu='yaourt -Syu'
# alias yua='yaourt -Sua'

alias ins='\/usr/bin/sudo apt-get install'
alias app='\/usr/bin/sudo apt-get'
#compdef app='apt-get'

alias n='urxvtcd -cd "$(pwd)"'
alias startx='startx &> ~/.Xlog'
alias pgd='\/usr/bin/sudo -bu postgres postgres -D /var/lib/postgres/data'
alias pgdf='\/usr/bin/sudo -u postgres postgres -D /var/lib/postgres/data'
alias jsw='jekyll serve --watch'
alias sys='\/usr/bin/sudo systemctl'
#compdef sys='systemctl'

alias e='$EDITOR'
alias d='cd ~/Desktop'
alias g='TZ=UTC git'
#compdef g='git'
alias r='rails'
alias l='ls'
alias le='ls -lah'
alias eg='grep -E'

alias brightness-HDMI1='xrandr --output HDMI1 --brightness'

alias nup='s ip link set wlan0 up'
alias ndn='s ip link set wlan0 down'
alias neber='sudo systemctl stop NetworkManager 2>/dev/null; sudo netctl switch-to Eber'
alias ncopley='sudo systemctl stop NetworkManager 2>/dev/null; sudo netctl switch-to mooseclubi'
alias nkent='sudo systemctl stop NetworkManager 2>/dev/null; sudo netctl switch-to kent-guest'
alias nmit='sudo systemctl stop NetworkManager 2>/dev/null; sudo netctl switch-to MIT'
alias nn='\/usr/bin/sudo netctl'
# compdef nn='netctl'
alias mr='\/usr/bin/sudo ip link set wlan0 down && \/bin/sudo macchanger -a wlan0'
alias gv='cd ~/Desktop/movie/YouTube && youtube-dl '

function mnt() {
	[[ "$1" == ,* ]] && 1="/dev/${1#,}"
	[[ "$2" == .* ]] && 2="/media/${2#.}"
	if [[ "$UID" == 0 ]]
		then mkdir -p "$2" && mount "$@"
		else udevil mount "$@"
	fi
}
function umnt() {
	[[ "$1" == ,* ]] && 1="/dev/${1#,}"
	[[ "$1" == .* ]] && 1="/media/${1#.}"
	if [[ "$UID" == 0 ]]
		then umount "$1" && rmdir "$1"
		else udevil umount "$@"
	fi
}

function popout() {
	mv "$1" .
	rmdir `dirname "$1"`
	mv `basename "$1"` `dirname "$1"`
}


alias cljfast='LEIN_FAST_TRAMPOLINE=1 lein trampoline run -m clojure.main'
alias cljrun='LEIN_FAST_TRAMPOLINE=1 lein trampoline run'

alias getime='\/usr/bin/sudo ntpd -q && \/bin/sudo hwclock -w'
alias wfi='\/usr/bin/sudo wifi-menu'

alias t='tmsu'
#compdef t='tmsu'
alias tt='tmsu tag'
